import React from "react";
import Head from "next/head";
import { sanityClient, urlFor } from "../../sanity";
import Header from "../../components/Header";
import Banner from "../../components/Banner";
import Link from "next/link";

const projects = ({ projects }) => {
  return (
    <div className='mx-auto max-w-7xl'>
      <Head>
        <title>Peter Nguyen Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Navbar */}
      <Header />
      <Banner />

      {/* posts */}
      <div className=' grid grid-cols-1 gap-3 p-6 sm:grid-cols-2 md:gap-6 md:p-6 lg:grid-cols-3'>
        {projects.map((post) => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className='group cursor-pointer overflow-hidden rounded-lg border'>
              {post.mainImage && (
                <img
                  className='h-60 w-full object-cover transition-transform duration-200 ease-in-out group-hover:scale-105'
                  src={urlFor(post.mainImage).url()}
                  alt=''
                />
              )}
              <div className='flex justify-between bg-white p-5'>
                <div>
                  <p className='text-lg font-bold'>{post.title}</p>
                  <p className='text-xs'>
                    {post.description} by {post.author.name}
                  </p>
                  <div className='mt-2 flex flex-wrap flex-cols'>
                    {post.categories.map((category) => (
                      <p className='text-xs text-center rounded-full border border-green-600 mt-1 mr-1 px-3 py-1 text-green-600'>
                        {category.title}
                      </p>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default projects;

export const getServerSideProps = async () => {
  const query = `*[_type == "post" && "Projects" in categories[]->title]{

      _id,
      title,
      slug,
      author -> {
        name,
        image
      },
      mainImage,
      categories[] -> {
      title
      },
    }`;

  const projects = await sanityClient.fetch(query);

  return {
    props: {
      projects,
    },
  };
};
